services:

  db:
    image: postgres:15
    container_name: fintech_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: ./backend
    container_name: fintech_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/fintech
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app


  nginx:
    image: nginx:latest
    container_name: fintech_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html


volumes:
  postgres_data: