@startuml APISurface

title API Surface

actor Frontend

rectangle "FastAPI" {

    component "/accounts"
    component "/transactions"
    component "/users"
    component "/transactions/import"

}

Frontend --> "/accounts"
Frontend --> "/transactions"
Frontend --> "/users"
Frontend --> "/transactions/import"

@enduml