@startuml classes_fintech_backend
set namespaceSeparator none
class "Account" as backend.app.models.account.Account {
  account_id
  account_type
  balance
  currency
  user_id
}
class "AccountCreate" as backend.app.models.schemas.AccountCreate {
  account_type : str
  currency : str
  user_id : UUID
}
class "AccountResponse" as backend.app.models.schemas.AccountResponse {
  account_id : UUID
  account_type : str
  balance : float | None
  currency : str
  user_id : UUID
}
class "Base" as backend.app.db.base.Base {
}
class "Config" as backend.app.models.schemas.TransactionResponse.Config {
  from_attributes : bool
}
class "Config" as backend.app.models.schemas.UserResponse.Config {
  from_attributes : bool
}
class "Config" as backend.app.models.schemas.AccountResponse.Config {
  from_attributes : bool
}
class "Transaction" as backend.app.models.transaction.Transaction {
  account_id
  amount
  balance
  category
  date
  description
  transaction_id
  user_id
}
class "TransactionCreate" as backend.app.models.schemas.TransactionCreate {
  account_id : UUID
  amount : float
  category : str | None
  date : date
  description : str | None
  user_id : UUID
}
class "TransactionResponse" as backend.app.models.schemas.TransactionResponse {
  account_id : UUID
  amount : float
  balance : float
  category : str | None
  date : date
  description : str | None
  transaction_id : UUID
  user_id : UUID
}
class "User" as backend.app.models.user.User {
  email
  user_id
}
class "UserCreate" as backend.app.models.schemas.UserCreate {
  email : str
}
class "UserResponse" as backend.app.models.schemas.UserResponse {
  email : str
  user_id : UUID
}
@enduml
