@startuml packages_fintech_backend
set namespaceSeparator none
package "backend" as backend {
}
package "backend.app" as backend.app {
}
package "backend.app.api" as backend.app.api {
}
package "backend.app.api.accounts" as backend.app.api.accounts {
}
package "backend.app.api.ingestion" as backend.app.api.ingestion {
}
package "backend.app.api.transactions" as backend.app.api.transactions {
}
package "backend.app.api.users" as backend.app.api.users {
}
package "backend.app.config" as backend.app.config {
}
package "backend.app.db" as backend.app.db {
}
package "backend.app.db.base" as backend.app.db.base {
}
package "backend.app.db.deps" as backend.app.db.deps {
}
package "backend.app.db.init_db" as backend.app.db.init_db {
}
package "backend.app.db.session" as backend.app.db.session {
}
package "backend.app.models" as backend.app.models {
}
package "backend.app.models.account" as backend.app.models.account {
}
package "backend.app.models.schemas" as backend.app.models.schemas {
}
package "backend.app.models.transaction" as backend.app.models.transaction {
}
package "backend.app.models.user" as backend.app.models.user {
}
package "backend.main" as backend.main {
}
backend.main --> backend.app.api.accounts
backend.main --> backend.app.api.ingestion
backend.main --> backend.app.api.transactions
backend.main --> backend.app.api.users
@enduml
